# Setup

In [1]:
import numpy as np
import tensorflow as tf
import tf_encrypted as tfe

Falling back to insecure randomness since the required custom op could not be found for the installed version of TensorFlow. Fix this by compiling custom ops. Missing file was 'F:\Anaconda3\envs\tfe\lib\site-packages\tf_encrypted/operations/secure_random/secure_random_module_tf_1.15.2.so'


In [ ]:
%load_ext tensorboard.notebook

TENSORBOARD_DIR = "/tmp/tensorboard"

tfe.set_tfe_trace_flag(True)
tfe.set_tfe_events_flag(True)
tfe.set_log_directory(TENSORBOARD_DIR)

# Protocol

We have to use the same configuration as used by the server, including player configuration and protocol.

In [ ]:
config = tfe.RemoteConfig.load("/tmp/tfe.config")

tfe.set_config(config)
tfe.set_protocol(tfe.protocol.Pond())

# Running

To run computations on the servers we create a new `tfe.serving.QueueClient`.

Note that we currently have to provide the input and output shapes for the computation (but not the computation itself)

In [ ]:
input_shape = (5, 5)
output_shape = (5, 5)

In [ ]:
client = tfe.serving.QueueClient(
    input_shape=input_shape,
    output_shape=output_shape)

In [ ]:
sess = tfe.Session(config=config)

In [7]:
res = client.run(
    sess,
    np.full(input_shape, 5))

print(res)

[[25.0 25.0 25.0 25.0 25.0]
 [25.0 25.0 25.0 25.0 25.0]
 [25.0 25.0 25.0 25.0 25.0]
 [25.0 25.0 25.0 25.0 25.0]
 [25.0 25.0 25.0 25.0 25.0]]
